<?php

namespace Tests\Unit\Services;

use App\Services\AgeDifferenceService;
use Tests\TestCase;

class AgeDifferenceServiceUnittest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function dataTestCaseProvider()
    {
        return [
            'Empty input' => [
                [], // Input
                []  // Expected output
            ],
            'Single person' => [
                [['age' => 30]],
                []
            ],
            'Two people' => [
                [['age' => 25], ['age' => 40]],
                []
            ],
            'Five people with close ages' => [
                [['age' => 22], ['age' => 25], ['age' => 28], ['age' => 30], ['age' => 35]],
                [['age' => 35]]
            ],
            'Ten people' => [
                [['age' => 18], ['age' => 20], ['age' => 22], ['age' => 24], ['age' => 26], ['age' => 28], ['age' => 30], ['age' => 32], ['age' => 34], ['age' => 36]],
                [['age' => 18],['age' => 36]]
            ],
        ];
    }

    /**
     * @test
     * @dataProvider dataTestCaseProvider
     */
    public function testFindTopAgeDifference($testCase, $expect)
    {
        $service = new AgeDifferenceService();
        $topPeople = $service->findTopAgeDifference($testCase);
        $this->assertEquals($expect, $topPeople);
    }
}
