<?php

namespace Tests\Unit\Services;

use App\Services\StudentAgeCounter;
use Tests\TestCase;

class StudentAgeCounterUnittest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function youngerThanThresholdProvider(): array
    {
        return [
            // Case 1: Một số tuổi nhỏ hơn 242
            'Case 1' => [
                [240, 242, 250, 260, 245, 238, 270, 241], // Danh sách học sinh
                242,  // Ngưỡng tuổi (20 năm 2 tháng)
                3     // Kết quả mong đợi: (240, 238, 241)
            ],
            // Case 2: Không có học sinh nào nhỏ hơn 242
            'Case 2' => [
                [250, 260, 270, 255, 248, 245],
                242,
                0
            ],
            // Case 3: Tất cả học sinh nhỏ hơn 242
            'Case 3' => [
                [230, 235, 240, 238, 239],
                242,
                5
            ],
        ];
    }

    /**
     * @test
     * @dataProvider youngerThanThresholdProvider
     */
    public function testCountYoungerThanThreshold($testCase, $threshold, $expectedCount)
    {
        $counter = new StudentAgeCounter($testCase);
        $this->assertEquals($expectedCount, $counter->countYoungerThanThreshold($threshold));
    }

    public function olderThanThresholdProvider(): array
    {
        return [
            // Case 1: Một số tuổi lớn hơn 254
            'Case 1' => [
                [240, 242, 250, 260, 245, 238, 270, 255],
                254,  // Ngưỡng tuổi (21 năm 2 tháng)
                3     // Kết quả mong đợi: (260, 270, 255)
            ],
            // Case 2: Không có học sinh nào lớn hơn 254
            'Case 2' => [
                [240, 242, 245, 250, 248],
                254,
                0
            ],
            // Case 3: Tất cả học sinh lớn hơn 254
            'Case 3' => [
                [255, 260, 270, 265, 280],
                254,
                5
            ],
        ];
    }

    /**
     * @test
     * @dataProvider olderThanThresholdProvider
     */
    public function testCountOlderThanThreshold($testCase, $threshold, $expectedCount)
    {
        $counter = new StudentAgeCounter($testCase);

        $this->assertEquals($expectedCount, $counter->countOlderThanThreshold($threshold));
    }
}
